# Generated by Django 4.2.5 on 2023-09-19 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.IntegerField()),
                ("date", models.CharField(max_length=50)),
                ("exception_type", models.IntegerField()),
            ],
            options={
                "verbose_name": "Calendar dates",
                "verbose_name_plural": "Calendar dates",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("route_id", models.IntegerField(primary_key=True, serialize=False)),
                ("route_short_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                ("stop_id", models.IntegerField(primary_key=True, serialize=False)),
                ("stop_code", models.IntegerField(null=True)),
                ("stop_name", models.CharField(max_length=255)),
                ("stop_latitude", models.CharField(max_length=36)),
                ("stop_longitude", models.CharField(max_length=36)),
                ("zone_id", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.IntegerField()),
                ("service_id", models.IntegerField()),
                ("trip_headsign", models.CharField(max_length=255)),
                ("direction_id", models.IntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.route"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StopTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.CharField(max_length=255)),
                ("departure_time", models.CharField(max_length=255)),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.stop"
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.trip"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stop times",
                "verbose_name_plural": "Stop times",
            },
        ),
    ]
