# Generated by Django 4.2.5 on 2023-09-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calendardates",
            options={
                "verbose_name": "Calendar dates",
                "verbose_name_plural": "Calendar dates",
            },
        ),
        migrations.AlterModelOptions(
            name="stoptimes",
            options={"verbose_name": "Stop times", "verbose_name_plural": "Stop times"},
        ),
    ]
