# Generated by Django 4.2.5 on 2024-04-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoptimes",
            name="stop_sequence",
            field=models.IntegerField(null=True, blank=False),
            preserve_default=False,
        ),
    ]
