# Generated by Django 4.2.5 on 2023-09-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_calendardates_options_alter_stoptimes_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="stop_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="zone_id",
            field=models.IntegerField(null=True),
        ),
    ]
