# Generated by Django 4.2.5 on 2023-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_stop_stop_code_alter_stop_zone_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="stop_latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="stop_longitude",
            field=models.FloatField(null=True),
        ),
    ]
