# Generated by Django 4.2.5 on 2023-09-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_stop_stop_latitude_alter_stop_stop_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendardates",
            name="date",
            field=models.CharField(max_length=50),
        ),
    ]
