# Generated by Django 4.2.5 on 2023-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_calendardates_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoptimes",
            name="arrival_time",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stoptimes",
            name="departure_time",
            field=models.CharField(max_length=255),
        ),
    ]
